name: Lands
main: world.avatarhorizon.spigot.lands.LandsPlugin
authors: [Nokorbis, Koudja]
version: 0.1.0
depend: [WorldEdit]
softdepend: [Multiverse]
commands:
    lands:
        description: Lands main command
        aliases: [ld, land]
        usage: /lands help
permissions:
    lands.*:
        description: Permission to access every command
        default: op
        children:
        - lands.admin.*
        - lands.commands.*
    lands.admin.*:
        description: Permission to access every ADMIN command
        default: false
        children:
        - lands.admin.create
        - lands.admin.rename
        - lands.admin.description
        - lands.admin.addchunks
        - lands.admin.removechunks
        - lands.admin.delete
        - lands.admin.setteleport
    lands.commands.*:
        description: Permission to access basic commands
        default: false
        children:
        - lands.commands.help
        - lands.commands.list
        - lands.commands.teleport
    lands.admin.create:
        description: Permission to create a new land
        default: false
    lands.admin.rename:
        description: Permission to rename a land
        default: false
    lands.admin.description:
        description: Permission to define the description of a land
        default: false
    lands.admin.addchunks:
        description: Permission to add chunks to a land
        default: false
    lands.admin.removechunks:
        description: Permission to remove chunks to a land
        default: false
    lands.admin.delete:
        description: Permission to delete a land.
        default: false
    lands.admin.setteleport:
        description: Permission to define the teleport location of a land
        default: false
    lands.commands.list:
        description: Permission to list lands
        default: false
    lands.commands.help:
        description: Permission to call the help command
        default: false
    lands.commands.teleport:
        description: Permission to teleport to a land's location
        default: false
