name: Lands
main: world.avatarhorizon.spigot.lands.LandsPlugin
authors: [Nokorbis, Koudja]
version: 0.1.0
depend: [WorldEdit]
softdepend: []
commands:
    lands:
        description: Lands main command
        aliases: [ld, land]
        usage: /lands help
permissions:
    lands.*:
        description: Permission to access every command
        default: op
        children:
        - lands.admin.*
    lands.admin.*:
        description: Permission to access every ADMIN command
        default: false
        children:
        - lands.admin.create
        - lands.admin.rename
        - lands.admin.description
        - lands.admin.help
    lands.admin.create:
        description: Permission to create a new land
        default: false
    lands.admin.rename:
        description: Permission to rename a land
        default: false
    lands.admin.description:
        description: Permission to define the description of a land
        default: false
    lands.admin.help:
        description: Permission to call the help command
        default: false

